-- Demo course data for mfms.html and mfms-detail.html
-- Run this after schema.sql and after seed-booking-demo.sql.

with course_data(
  slug,
  club_slug,
  title,
  english_club,
  level,
  mode,
  time_text,
  schedule,
  location,
  seats,
  fee_text,
  description,
  lead,
  detail,
  coach_name,
  coach_title,
  coach_bio,
  learning_points,
  audience_tips,
  notes_list,
  popularity
) as (
  values
    (
      'badminton-serve-fundamentals',
      'badminton',
      'Badminton Serve Fundamentals (Beginner)',
      'Badminton Club',
      'Beginner',
      'In-person',
      'Wed 19:00-20:00',
      array['Wed 19:00-20:00', 'Sun 09:30-10:30']::text[],
      'Indoor Hall B (In-person)',
      12,
      '£0',
      'Grip, stance, and serve mechanics broken down with guided practice.',
      'Build a reliable service action and a calmer first touch from the back court.',
      'This course covers the key basics of forehand and backhand serving, common error correction, and practice suggestions to help beginners build a stable serve.',
      'Alex Chen',
      'Badminton Intensive Coach',
      'Focuses on technical breakdowns, rhythm, and class feedback for beginners.',
      array['Build a stable grip and clean serve rhythm', 'Improve contact point consistency', 'Practise targeted corrections with guided drills']::text[],
      array['Suitable for complete beginners', 'Helpful if you want a simple weekly badminton routine', 'Best if you want in-person correction and repeated serve practice']::text[],
      array['Bring indoor sports shoes and a racket if you have one', 'Arrive 10 minutes early to warm up', 'If you need to cancel, try to release the seat 24 hours in advance']::text[],
      42
    ),
    (
      'football-passing-basics',
      'football',
      'Football Ball Control and Passing Basics (Beginner)',
      'Football Club',
      'Beginner',
      'In-person',
      'Tue 18:00-19:30',
      array['Tue 18:00-19:30', 'Sat 15:00-16:30']::text[],
      'Stadium A (In-person)',
      15,
      '£0',
      'Ball control, short passing, two-player coordination, and simple opposition drills.',
      'A steady entry course for learners who want to improve first touch and simple passing patterns.',
      'Designed for beginners, this course builds ball control and passing fundamentals with inside-foot and instep passing, first-touch breakdowns, and small-group combinations.',
      'Ryan Zhao',
      'Football Specialist Coach',
      'Specialises in passing control, movement, and live-play feedback.',
      array['Improve first touch and short-pass accuracy', 'Understand basic movement after passing', 'Build confidence through small-group game drills']::text[],
      array['Good for new club members', 'Useful if you want regular in-person football training', 'Suitable for learners who prefer guided practical drills over theory']::text[],
      array['Wear appropriate boots or trainers for the field', 'Bring water and light training gear', 'Warm up with the group before the main session starts']::text[],
      55
    ),
    (
      'swimming-breathing-and-stroke',
      'swimming',
      'Freestyle Beginner: Breathing and Stroke',
      'Swimming Club',
      'Beginner',
      'In-person',
      'Sat 10:00-11:00',
      array['Sat 10:00-11:00', 'Wed 07:30-08:30']::text[],
      'Aquatics Center (In-person)',
      18,
      '£2/session',
      'Breathing rhythm, stroke motion, and basic coordination drills.',
      'A beginner-friendly class that rebuilds body position and breathing confidence in the water.',
      'This course focuses on freestyle fundamentals, especially breathing rhythm and stroke coordination, making it a strong fit for complete beginners or learners rebuilding basics.',
      'Mia Wang',
      'Swimming Instructor',
      'Provides breathing, stroke, and endurance guidance for mixed-level swimmers.',
      array['Build a smoother breathing rhythm', 'Improve arm-leg coordination in freestyle', 'Strengthen body position and pacing awareness']::text[],
      array['Suitable for learners rebuilding swimming basics', 'Helpful if you want structured pool sessions', 'Best for members who want guided correction and technique practice']::text[],
      array['Bring goggles, swimwear, and a towel', 'Follow pool safety guidance at all times', 'Tell the coach early if you need a lower-intensity lane']::text[],
      60
    ),
    (
      'cycling-route-planning',
      'cycling',
      'Cycling Route Planning and Group Ride Basics',
      'Cycling Club',
      'Beginner',
      'Hybrid',
      'Thu 18:30-19:30',
      array['Thu 18:30-19:30', 'Sun 09:00-10:00']::text[],
      'Meeting point: Campus Gate (In-person) / group updates (Online)',
      20,
      '£0',
      'Route awareness, pace communication, and safe group ride habits for new riders.',
      'Learn how to join club rides confidently with a clear understanding of basic pacing and route preparation.',
      'This hybrid course introduces safe group ride routines, route planning basics, and communication habits that help new members join city rides more comfortably.',
      'Liam Sun',
      'Cycling Route Mentor',
      'Supports beginner riders with route planning and group-ride safety habits.',
      array['Understand basic route planning and ride pacing', 'Learn simple hand signals and ride communication', 'Prepare for weekend club rides with more confidence']::text[],
      array['Great for riders new to group cycling', 'Useful if you want both online updates and in-person rides', 'Suitable for members building weekend ride confidence']::text[],
      array['Check tyres and brakes before the session', 'Bring a helmet and water bottle', 'Join the group chat early for route updates and weather notes']::text[],
      38
    ),
    (
      'programming-html-css-foundations',
      'programming',
      'Web Frontend Beginner: HTML/CSS Fundamentals',
      'Programming Club',
      'Beginner',
      'Online',
      'Fri 20:00-21:30',
      array['Fri 20:00-21:30', 'Tue 20:00-21:30']::text[],
      'Online meeting link (Virtual)',
      40,
      '£0',
      'Page structure and base styling for building a simple website.',
      'A practical first step for members who want to build small frontend pages with confidence.',
      'From HTML structure to CSS layout basics, this course explains common page patterns and component thinking, making it useful for course projects and personal portfolios.',
      'Ethan Zhou',
      'Frontend Course Instructor',
      'Teaches reusable page structure and practical web development habits.',
      array['Understand HTML page structure and semantics', 'Build basic layouts with CSS', 'Practise turning ideas into a small static page']::text[],
      array['Great for complete beginners to web development', 'Suitable for learners who want flexible remote participation', 'Useful if you are preparing coursework or a portfolio page']::text[],
      array['Join the online room a few minutes early', 'Keep your editor ready for live coding practice', 'Ask questions in chat if you need a slower pace during demos']::text[],
      70
    ),
    (
      'tennis-serve-and-rally-basics',
      'tennis',
      'Tennis Forehand, Backhand, and Serve Basics',
      'Tennis Club',
      'Beginner',
      'In-person',
      'Sat 14:00-15:30',
      array['Sat 14:00-15:30', 'Mon 18:30-20:00']::text[],
      'Tennis Court C (In-person)',
      10,
      '£2/session',
      'Core forehand and backhand technique, serve basics, and simple rally practice.',
      'Learn the main stroke patterns and start building more stable rally rhythm.',
      'This course covers grip and swing-path correction, forehand and backhand consistency, and the fundamentals of serving with practical training methods.',
      'Emma Lin',
      'Tennis Foundations Coach',
      'Helps beginners build reliable strokes and steadier rally rhythm.',
      array['Understand basic forehand and backhand mechanics', 'Build confidence in simple serve practice', 'Improve consistency through short rally drills']::text[],
      array['Suitable for beginners and returning players', 'Best if you want live correction on court', 'Helpful for members preparing for casual weekend games']::text[],
      array['Bring a racket if you have one', 'Wear comfortable court shoes', 'Arrive early for the shared warm-up and mobility work']::text[],
      33
    ),
    (
      'music-ensemble-rehearsal-skills',
      'music',
      'Ensemble Rehearsal and Stage Coordination',
      'Music Society',
      'Beginner',
      'Hybrid',
      'Wed 18:30-20:00',
      array['Wed 18:30-20:00', 'Sat 11:00-12:30']::text[],
      'Arts Building 2F / online sharing',
      18,
      '£0',
      'Rehearsal structure, listening cues, and stage coordination for small performances.',
      'A supportive music course for members preparing for showcases and group rehearsals.',
      'This hybrid course helps members understand rehearsal flow, listening cues, and performance coordination so they can take part in ensemble sessions with more confidence.',
      'Sophie He',
      'Ensemble Director',
      'Guides rehearsal structure, listening awareness, and stage coordination.',
      array['Understand rehearsal roles inside an ensemble', 'Improve cue listening and group timing', 'Prepare for small stage showcases with more confidence']::text[],
      array['Suitable for singers and instrumentalists', 'Useful if you want hybrid rehearsal support', 'Great for members preparing for society showcases']::text[],
      array['Bring your own instrument when needed', 'Review shared sheet music before class', 'Online participants should test audio devices before rehearsal']::text[],
      29
    ),
    (
      'running-endurance-rhythm',
      'running',
      'Running Endurance Rhythm and Pacing',
      'Running Club',
      'Beginner',
      'In-person',
      'Tue 07:00-08:00',
      array['Tue 07:00-08:00', 'Sat 08:00-09:00']::text[],
      'Track meeting point (In-person)',
      24,
      '£0',
      'Build an easier running rhythm with guided pacing and steady endurance work.',
      'Develop a consistent training habit and better control over pace and recovery.',
      'This course is designed for members who want to improve pacing, breathing, and endurance through structured track sessions and weekly running goals.',
      'Noah Yu',
      'Endurance Coach',
      'Supports pacing, endurance planning, and safe weekly progress.',
      array['Improve pace awareness during group runs', 'Build a steadier breathing rhythm', 'Develop a weekly endurance routine you can maintain']::text[],
      array['Suitable for members starting a regular running habit', 'Helpful if you want guided group pacing', 'Good for learners preparing for longer club runs later']::text[],
      array['Bring water and suitable running shoes', 'Arrive a few minutes early for warm-up laps', 'Follow your own pace and communicate if you need a shorter interval set']::text[],
      44
    ),
    (
      'basketball-shooting-and-spacing',
      'basketball',
      'Basketball Shooting Rhythm and Team Spacing',
      'Basketball Club',
      'Beginner',
      'In-person',
      'Thu 19:00-20:30',
      array['Thu 19:00-20:30', 'Sun 16:00-17:30']::text[],
      'Basketball Court D (In-person)',
      18,
      '£0',
      'Shooting form, spacing, and small-sided teamwork drills.',
      'A practical class for members who want better shooting confidence and court movement.',
      'This course helps learners improve shooting rhythm, basic court spacing, and simple teamwork patterns through repeatable in-person drills.',
      'Jason Gu',
      'Basketball Skills Coach',
      'Focuses on shooting mechanics, spacing, and small-group teamwork practice.',
      array['Improve set-shot rhythm and balance', 'Understand basic off-ball spacing', 'Practise team communication through half-court drills']::text[],
      array['Suitable for members improving game basics', 'Helpful if you want more structured court practice', 'Great for learners who prefer active drills and live feedback']::text[],
      array['Bring appropriate indoor shoes', 'Join the shared warm-up before shooting drills', 'If you need a lighter load, tell the coach early in the session']::text[],
      47
    ),
    (
      'golf-swing-basics',
      'golf',
      'Golf Swing Basics and Weekend Practice',
      'Golf Club',
      'Beginner',
      'In-person',
      'Sat 09:30-11:00',
      array['Sat 09:30-11:00', 'Wed 18:00-19:00']::text[],
      'Practice Ground E (In-person)',
      12,
      '£5/session (Optional)',
      'Introductory swing practice, posture correction, and guided range routines.',
      'A calm entry course for members who want a more structured start to golf practice.',
      'This course introduces posture, grip, swing sequencing, and range habits so new members can practise more confidently and build a cleaner motion over time.',
      'Daniel Xu',
      'Golf Practice Mentor',
      'Supports beginner-friendly swing practice and steady range habits.',
      array['Learn a more stable setup and grip', 'Understand the main phases of a basic swing', 'Use simple range drills to build consistency']::text[],
      array['Great for complete beginners to golf', 'Helpful if you want weekend guided range sessions', 'Suitable for members who prefer slower, technique-led classes']::text[],
      array['Wear comfortable practice clothing', 'Bring clubs if you own them, but loan equipment may be available', 'Follow range safety instructions at all times']::text[],
      21
    ),
    (
      'rugby-contact-and-shape',
      'rugby',
      'Rugby Shape, Contact Prep, and Team Structure',
      'Rugby Club',
      'Advanced',
      'In-person',
      'Wed 19:00-20:30',
      array['Wed 19:00-20:30', 'Sat 13:00-14:30']::text[],
      'Stadium F (In-person)',
      20,
      '£0',
      'Structured tactical sessions on team shape, contact prep, and live drill execution.',
      'A higher-intensity class for members improving tactical understanding and live decision-making.',
      'This advanced course combines tactical structure, contact-preparation drills, and live-play situations so regular players can improve team shape and game awareness.',
      'Harvey Peng',
      'Rugby Tactical Coach',
      'Works on tactical structure, contact preparation, and match-style progression.',
      array['Improve team shape and transition awareness', 'Refine contact-preparation habits in drills', 'Build stronger communication in live rugby scenarios']::text[],
      array['Best for members with prior rugby experience', 'Suitable for learners preparing for external fixtures', 'Helpful if you want more tactical and physical training content']::text[],
      array['Bring appropriate training boots and protection', 'Hydrate well before the session', 'Follow the coach on contact intensity and safety progression']::text[],
      36
    ),
    (
      'handball-attack-defense-core',
      'handball',
      'Handball Attack, Defense, and Core Coordination',
      'Handball Club',
      'Beginner',
      'In-person',
      'Fri 18:30-20:00',
      array['Fri 18:30-20:00', 'Sun 15:00-16:30']::text[],
      'Sports Hall G (In-person)',
      16,
      '£0',
      'Passing movement, attack-defense rhythm, and coordinated team drills.',
      'A solid starting point for members learning the structure of handball movement and teamwork.',
      'This course helps new members understand handball attack and defense flow through footwork, passing, and team coordination drills designed for steady skill development.',
      'Ivy Luo',
      'Handball Team Coach',
      'Supports beginners with coordinated attack and defense practice.',
      array['Understand the main attack and defense structure', 'Improve passing rhythm under movement', 'Practise coordinated positioning with team drills']::text[],
      array['Suitable for members new to handball', 'Helpful if you want structured indoor team training', 'Good for learners who enjoy fast-paced coordination drills']::text[],
      array['Wear suitable indoor shoes', 'Bring water and knee support if needed', 'Join the coach-led mobility warm-up before team drills begin']::text[],
      26
    ),
    (
      'gymnastics-core-movement-flexibility',
      'gymnastics',
      'Gymnastics Core Movement and Flexibility Basics',
      'Gymnastics Club',
      'Beginner',
      'In-person',
      'Mon 18:00-19:00',
      array['Mon 18:00-19:00', 'Thu 17:30-18:30']::text[],
      'Gym Hall H (In-person)',
      14,
      '£0',
      'Flexibility work, core positions, and guided movement patterns for new members.',
      'Build a safer movement base and more confidence in flexibility-focused practice.',
      'This course focuses on flexibility, basic body positions, and controlled movement patterns to help beginners build better awareness and steadier practice habits in gymnastics.',
      'Olivia Tang',
      'Gymnastics Fundamentals Coach',
      'Guides body control, flexibility progressions, and safe beginner routines.',
      array['Improve flexibility with guided progressions', 'Build confidence in basic body positions', 'Practise safer movement patterns with coach support']::text[],
      array['Suitable for beginners to gymnastics', 'Helpful if you want structured flexibility practice', 'Good for learners who want low-pressure guided sessions']::text[],
      array['Wear comfortable movement clothing', 'Warm up properly before flexibility work', 'Move at your own range and tell the coach if you feel strain']::text[],
      24
    )
)
insert into public.courses (
  slug,
  club_id,
  title,
  english_club,
  level,
  mode,
  time_text,
  schedule,
  location,
  seats,
  fee_text,
  description,
  lead,
  detail,
  coach_name,
  coach_title,
  coach_bio,
  learning_points,
  audience_tips,
  notes_list,
  owner_id,
  popularity
)
select
  course_data.slug,
  clubs.id,
  course_data.title,
  course_data.english_club,
  course_data.level,
  course_data.mode,
  course_data.time_text,
  course_data.schedule,
  course_data.location,
  course_data.seats,
  course_data.fee_text,
  course_data.description,
  course_data.lead,
  course_data.detail,
  course_data.coach_name,
  course_data.coach_title,
  course_data.coach_bio,
  course_data.learning_points,
  course_data.audience_tips,
  course_data.notes_list,
  clubs.owner_id,
  course_data.popularity
from course_data
join public.clubs
  on clubs.slug = course_data.club_slug
on conflict (slug) do update
set
  club_id = excluded.club_id,
  title = excluded.title,
  english_club = excluded.english_club,
  level = excluded.level,
  mode = excluded.mode,
  time_text = excluded.time_text,
  schedule = excluded.schedule,
  location = excluded.location,
  seats = excluded.seats,
  fee_text = excluded.fee_text,
  description = excluded.description,
  lead = excluded.lead,
  detail = excluded.detail,
  coach_name = excluded.coach_name,
  coach_title = excluded.coach_title,
  coach_bio = excluded.coach_bio,
  learning_points = excluded.learning_points,
  audience_tips = excluded.audience_tips,
  notes_list = excluded.notes_list,
  owner_id = excluded.owner_id,
  popularity = excluded.popularity;
